import { BrowserWindow, globalShortcut, safeStorage } from 'electron';
import { join } from 'node:path';
import { openDatabase } from './db';
import { NoteStore } from './db/store';
import { HotkeyManager } from './hotkey';
import { registerIpcHandlers } from './ipc-handlers';
import { IpcChannels } from '@shared/ipc';
import type { LLMClient } from './llm/client';
import { createLLMClient } from './llm/factory';
import { Pipeline, type PipelineEventType } from './pipeline';
import { platformBinaryDir, userDataPath } from './paths';
import { SettingsStore, type Settings } from './settings';
import { AudioPreprocessor } from './whisper/audio-preprocessor';
import { WhisperModelManager } from './whisper/model-manager';
import { DEFAULT_MODEL_KEY, MODEL_REGISTRY } from './whisper/registry';
import { WhisperRunner } from './whisper/whisper-runner';

export interface Services {
  store: NoteStore;
  settings: SettingsStore;
  pipeline: Pipeline;
  audioDir: string;
}

export async function createServices(getWindows: () => BrowserWindow[]): Promise<Services> {
  const dbPath = userDataPath('app.db');
  const db = openDatabase(dbPath);

  const store = new NoteStore(db);
  const settings = new SettingsStore(db, safeStorage);

  const binDir = platformBinaryDir();
  const ext = process.platform === 'win32' ? '.exe' : '';
  const ffmpegPath = join(binDir, `ffmpeg${ext}`);
  const whisperPath = join(binDir, `whisper${ext}`);

  const modelManager = new WhisperModelManager({
    dir: userDataPath('models'),
    registry: MODEL_REGISTRY,
    onProgress: (key, bytes) => {
      for (const w of getWindows()) {
        w.webContents.send('model:progress', { key, bytes });
      }
    },
  });

  const modelPath = await modelManager.ensure(DEFAULT_MODEL_KEY);

  const audio = new AudioPreprocessor({
    ffmpegPath,
    tmpDir: userDataPath('tmp'),
  });
  const whisper = new WhisperRunner({ whisperPath, modelPath });

  let broadcast: (e: {
    type: PipelineEventType;
    payload: { id: string; markdown?: string };
  }) => void = () => {};

  const makeLLMClient = (s: Settings): LLMClient => {
    if (process.env['VINU_LLM_FAKE'] === '1') {
      return {
        async *streamNotes() {
          yield { delta: '# Test note\n\nGenerated by E2E.' };
        },
      };
    }
    return createLLMClient(s);
  };

  const pipeline = new Pipeline({
    store,
    audio,
    whisper,
    makeLLMClient,
    settings: () => settings.read(),
    emit: (type, payload) => broadcast({ type, payload }),
  });

  const audioDir = userDataPath('audio');

  const handlers = registerIpcHandlers({
    store,
    settings,
    pipeline,
    audioDir,
    windows: getWindows,
  });
  broadcast = handlers.broadcastNotesEvent;

  const hotkey = new HotkeyManager({
    globalShortcut,
    onPress: () => {
      for (const w of getWindows()) {
        w.webContents.send(IpcChannels.HotkeyPressed);
        if (!w.isVisible()) w.show();
        w.focus();
      }
    },
  });
  const applyHotkey = () => {
    const s = settings.read();
    hotkey.apply({ enabled: s.hotkeyEnabled, accelerator: s.hotkeyAccelerator });
  };
  applyHotkey();

  const origWrite = settings.write.bind(settings);
  settings.write = (next) => {
    origWrite(next);
    applyHotkey();
  };

  return { store, settings, pipeline, audioDir };
}
